# Generated by Django 4.2.5 on 2023-09-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningplatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Articles2',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
