# Generated by Django 4.2.5 on 2023-09-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningplatform', '0002_rename_articles_articles2_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videotutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele', models.CharField(max_length=50)),
                ('video', models.URLField(max_length=500)),
            ],
        ),
    ]
