# Generated by Django 4.1.5 on 2023-10-11 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elearningplatform', '0004_rename_titele_videotutorial_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
