# Generated by Django 4.1.5 on 2023-10-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningplatform', '0005_videotutorial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multichoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
