# Generated by Django 4.2.5 on 2023-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningplatform', '0007_quesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200, null=True)),
                ('A', models.CharField(max_length=200, null=True)),
                ('B', models.CharField(max_length=200, null=True)),
                ('C', models.CharField(max_length=200, null=True)),
                ('D', models.CharField(max_length=200, null=True)),
                ('Answer', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
