# Generated by Django 4.2.5 on 2023-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningplatform', '0008_add_questions_delete_quesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_questions',
            name='Answer_expalanation',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='add_questions',
            name='E',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='add_questions',
            name='A',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='add_questions',
            name='Answer',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='add_questions',
            name='B',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='add_questions',
            name='C',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='add_questions',
            name='D',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='add_questions',
            name='Question',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
